# Generated by Django 6.0.4 on 2026-04-29 01:29

from django.db import migrations, models
import random


def populate_library_ids(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    used = set(CustomUser.objects.exclude(library_id__isnull=True).exclude(library_id="").values_list("library_id", flat=True))
    for user in CustomUser.objects.all():
        if user.library_id:
            continue
        while True:
            candidate = str(random.randint(10000000, 99999999))
            if candidate not in used:
                user.library_id = candidate
                user.save(update_fields=["library_id"])
                used.add(candidate)
                break


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_migrate_student_to_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='library_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.RunPython(populate_library_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='library_id',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
