# Generated by Django 6.0.3 on 2026-04-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_librarian_flags'),
        ('accounts', '0004_customuser_library_id'),
    ]

    operations = [
    ]
