# Generated by Django 6.0.4 on 2026-04-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Active', max_length=20),
        ),
    ]
