# Generated by Django 6.0.4 on 2026-04-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_alter_borrowrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Active', 'Active'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Pending', max_length=20),
        ),
    ]
